name: Build and Auto-Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install pyinstaller pillow pystray requests arabic-reshaper python-bidi pygame geocoder

    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile --name "Prayer_Station" main.py

    - name: Create Zip Package
      run: |
        mkdir release_folder
        copy dist\Prayer_Station.exe release_folder\
        copy adhan.mp3 release_folder\
        powershell Compress-Archive -Path release_folder\* -DestinationPath Prayer_Station_v0.6.zip

    - name: Auto-Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: Prayer_Station_v0.6.zip
        tag_name: v0.6
        name: Prayer Station v0.6 ðŸ‡¸ðŸ‡¦
        body: |
          Automatic Build by GitHub Actions.
          - Added Gaming HUD (Mini-Mode)
          - Added Auto-Location detection
          - Coded by MH7Q ðŸ‡¸ðŸ‡¦
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}